# Export scale-related utilities for convenient access
from src.utils.object_scale import (
    ObjectScale,
    COCO_SCALE_THRESHOLDS,
    SCALE_COLORS_BGR,
    SCALE_COLORS_RGB,
    SCALE_COLORS_NORMALIZED,
    SCALE_LABELS,
    classify_scale,
    classify_scale_from_dimensions,
    get_scale_color_bgr,
    get_scale_color_rgb,
    get_scale_color_normalized,
    get_scale_color_for_area,
    get_scale_label,
    get_area_range_for_scale,
    ScaleStatistics,
    compute_scale_statistics,
    filter_boxes_by_scale,
    group_boxes_by_scale,
)

__all__ = [
    'ObjectScale',
    'COCO_SCALE_THRESHOLDS',
    'SCALE_COLORS_BGR',
    'SCALE_COLORS_RGB',
    'SCALE_COLORS_NORMALIZED',
    'SCALE_LABELS',
    'classify_scale',
    'classify_scale_from_dimensions',
    'get_scale_color_bgr',
    'get_scale_color_rgb',
    'get_scale_color_normalized',
    'get_scale_color_for_area',
    'get_scale_label',
    'get_area_range_for_scale',
    'ScaleStatistics',
    'compute_scale_statistics',
    'filter_boxes_by_scale',
    'group_boxes_by_scale',
]
