# Export scale-related utilities for convenient access
from src.utils.object_scale import (
    ObjectScale,
    COCO_SCALE_THRESHOLDS,
    SCALE_COLORS_BGR,
    SCALE_COLORS_RGB,
    SCALE_COLORS_NORMALIZED,
    SCALE_LABELS,
    classify_scale,
    classify_scale_from_dimensions,
    get_scale_color_bgr,
    get_scale_color_rgb,
    get_scale_color_normalized,
    get_scale_color_for_area,
    get_scale_label,
    get_area_range_for_scale,
    ScaleStatistics,
    compute_scale_statistics,
    filter_boxes_by_scale,
    group_boxes_by_scale,
)

# Export color analysis utilities for bias profiling
from src.utils.color_analysis import (
    ColorAnalysisResult,
    extract_roi,
    find_dominant_color,
    create_color_mask,
    calculate_center_of_gravity,
    analyze_bounding_box_color,
    analyze_bounding_box_from_bb,
    draw_crosshair_marker,
    add_color_marker_to_bb,
)

__all__ = [
    # Scale utilities
    'ObjectScale',
    'COCO_SCALE_THRESHOLDS',
    'SCALE_COLORS_BGR',
    'SCALE_COLORS_RGB',
    'SCALE_COLORS_NORMALIZED',
    'SCALE_LABELS',
    'classify_scale',
    'classify_scale_from_dimensions',
    'get_scale_color_bgr',
    'get_scale_color_rgb',
    'get_scale_color_normalized',
    'get_scale_color_for_area',
    'get_scale_label',
    'get_area_range_for_scale',
    'ScaleStatistics',
    'compute_scale_statistics',
    'filter_boxes_by_scale',
    'group_boxes_by_scale',
    # Color analysis utilities
    'ColorAnalysisResult',
    'extract_roi',
    'find_dominant_color',
    'create_color_mask',
    'calculate_center_of_gravity',
    'analyze_bounding_box_color',
    'analyze_bounding_box_from_bb',
    'draw_crosshair_marker',
    'add_color_marker_to_bb',
]
